image:
  file: gitpod.Dockerfile
tasks:
  - name: tailscaled
    command: |
      sudo tailscaled
  - name: tailscale
    command: |
      sudo -E tailscale up --hostname "gitpod-${GITPOD_GIT_USER_NAME// /-}-$(echo ${GITPOD_WORKSPACE_CONTEXT} | jq -r .repository.name)" \
                           --authkey "${TAILSCALE_AUTHKEY}"

experimentalNetwork: true
